# Site settings
title: Chico State Web Dev and Design Club
email: csuwebdev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Become a better web developer, network with others, build teamwork
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://csuwebdev.com" # the base hostname & protocol for your site

collections:
  events:
    output: true
    permalink: /events/:path/

# Build settings
markdown: kramdown
